### ISSUE TITLE
inconsistent information

### ISSUE THREAD

**Issue by valorloff** [jthegedus/firebase-functions-next-example#10]
Hi!
impossible to enjoy by this example:
1. `firebase serve` command fire hosting only. Maybe need `firebase serve --only functions,hosting` ?
2. In Medium post says about necessity moving functions to src folder with appropriate firebase.json:
```
{
  "hosting": {
    "public": "src/public"
  },
  "functions": {
    "source": "src/functions"
  }
}
```
In your example functions/next folder created in dist folder:

```
{
  "hosting": {
    "public": "dist/public",
    "rewrites": [
      {
        "source": "**/**",
        "function": "next"
      }
    ]
  },
  "functions": {
    "source": "dist/functions"
  }
}
```
3. `process.env.NODE_ENV` in functions does not defined at all 

in this state, the example (with `serve --only functions, hosting`) on http://localhost:5000 return error:

`function info: Execution took 3644 ms, finished with status: 'crash'`
in browser:
`{"error":{"code":500,"status":"INTERNAL","message":"function crashed","errors":["socket hang up"]}}
`
what is for 
`"build-functions": "babel \"src/functions\" --out-dir \"dist/functions\" --copy-files"` ?

also takes place favicon problem
```
exports.next = functions.https.onRequest((req, res) => {
    console.log('File: ' + req.originalUrl);
// File: /favicon.ico

``` 

please give the correct working version, so that we're can try, how it works,
thanks

**Comment by jthegedus** [comment]
@valorloff Hey, thanks for the feedback. The codebase here is the canonical way to use Next.js with Firebase. I understand the frustration when the Medium post is out of date, this annoys me too. Unfortunately, articles and blogs are never going to be as up to date as the code, although I do have a new solution I've been working on that may help my posts avoid this in the future.

I'll be updating this code over the weekend and making a new blog post covering the new implementation of the code and with a test of the new method for keeping my blog up to date. The new code will solve problem 2.

Regarding problem 1. `firebase serve --only functions,hosting`, please see my longer response here 
https://github.com/zeit/next.js/issues/3167 . I've had more time to think on this and so may attempt to solve this problem another way in the future.

3. This is a way to configure next.js to compile a Production version of your app. Without a `.env` file setting `NODE_ENV = production` the value of `dev` is true, setting Next.js to be in dev mode. This enables better errors etc when developing. If you do add a `.env` that sets `NODE_ENV=production` then a production build will occur which will be more performant. 
```js
var dev = process.env.NODE_ENV !== "production"
var app = nextApp({ dev, conf: { distDir: "next" } })
```
It's up to the user to set the `.env` vars and so this package defaults to dev mode.

I will add a favicon to the project to remove that error :+1: 

Thanks for taking the time to write a thorough issue :1st_place_medal: I will try and address each of your concerns over the next week :smile:

**Comment by valorloff** [comment]
sorry that late, 
excellent answer!

**Comment by jthegedus** [comment]
I'll be updating this in the near future with that blog post I've been putting off for 6 months! Time flies! Next.js has been through so many iterations now it's hard to stay on top of it all!

Rest assured, a long-term solution is coming
