### ISSUE TITLE
Add SCSS/SASS import

### ISSUE THREAD

**Issue by dmitryrn** [jthegedus/firebase-functions-next-example#13]
Hi! Very love your solution!

Can you add example which can explain how to import SCSS/SASS to .js or compile them to file (.css).

Thank you!

**Comment by jthegedus** [comment]
@DmitryGG I will indeed. This has been a heavily requested example! It may take some time :sweat_smile:

**Comment by dmitryrn** [comment]
@jthegedus if you want to watch how I did it then check https://github.com/DmitryGG/react-ssr-firebase-sass

**Comment by jthegedus** [comment]
Cheers for the link.

I will close this issue as when I do get around to doing the Sass example I will be posting it to https://github.com/jthegedus/blog-code
