### ISSUE TITLE
how to user a custom HTML template for render 

### ISSUE THREAD

**Issue by yestoall** [jthegedus/firebase-functions-next-example#14]
my client is using a template HTML page where i need to insert my nextjs application

this template is changing in real time, so i need to implement a render version of nextjs application with this template

which is the best way to do that?

**Comment by yestoall** [comment]
i mean... insert my nextjs application in this HMTL template

**Comment by jthegedus** [comment]
@yestoall The only way I can think of this possibly working is with a [static export of the Next.js application](https://github.com/zeit/next.js#static-html-export) before embedding it within the HTML template. I've no idea how you would actually go about embedding it into an HTML template though.

**Comment by timneutkens** [comment]
It's simply hard to do, you can render to a string though, similar to next export.  But you'd have to parse the body only, and even then Next might not be the greatest fit because it's focused on full pages.

**Comment by jthegedus** [comment]
@yestoall Sorry for not being able to help more on this, but given Tim's input, I would agree that Next.js is probably not the right tool for the use case you want to achieve.

I would suggest that you raise this issue with whichever tool it is that you use for your HTML templates.
