### ISSUE TITLE
style jsx doesn't work on firebase but does on local dev server

### ISSUE THREAD

**Issue by uncleGena** [jthegedus/firebase-functions-next-example#18]
When I add this code to my component 

    <style jsx>{`
      
      .header {
        flex: 0 0 50px;
        justify-content: center;
        align-items: center;
        display: flex;
      }

      .header__conteainer {
        
      }

      .header__link {
        margin: 0 20px;
      }

    `}</style>

it works fine on `yarn dev` but when I do `yarn deploy-app` it deploys successfully and when I load page (on firebase) I see 500 error. And in console `500 - Internal Server Error.
undefined`

ubuntu 18 (pop os)
also I use nvm and node v6.11.5
steps to reproduce:
1. clone the project
2. past that code right above closing `</header>` in Header.js
3. run `yarn deploy-app`

**Comment by jthegedus** [comment]
I have not tried `styled-jsx` with Firebase since https://github.com/zeit/next.js/issues/3434

Could try the solution provided there and get back to me about whether or not it works with this current example?

**Comment by jthegedus** [comment]
@uncleGena I hope you found a solution you are happy with. Sorry I wasn't more help at the time.

Onward and upwards! I am deprecating this example in favor of another approach, which can be found in this repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).

I've been very busy the last few months and getting back into the swing of OSS and writing so if you are having issues I will truly try and be more prompt next time. Cheers.
