### ISSUE TITLE
Why the projcet dont have a <Head> component?

### ISSUE THREAD

**Issue by CharlyJazz** [jthegedus/firebase-functions-next-example#19]
Like that: 

![image](https://user-images.githubusercontent.com/12489333/41565538-32615210-7325-11e8-93f0-bbd95a94579c.png)

Is this not a problem, right?

**Comment by jthegedus** [comment]
This was just a minimal example of getting an SSR framework with Firebase Cloud Functions and Firebase Hosting working. I intend to cover more exhaustive examples in my other repo (https://github.com/jthegedus/blog-code) in the very near future!
