### ISSUE TITLE
@google-cloud/functions-emulator | Suggested Solution 

### ISSUE THREAD

**Issue by mtx62** [jthegedus/firebase-functions-next-example#23]
Hello,
I'm sorry if I'm writing in the wrong place but I have a suggested solution for @google-cloud/functions-emulator error and it's working with node 8 >= and I don't know where to write it except here.

For me, the solution was uninstalled `firebase-tools` from the project and install it globally using npm 
`npm install -g firebase-tools`

after that I changed the script in `package.json` to be:
`    "serve": "NODE_ENV=production firebase serve --only functions,hosting",`
`    "deploy-app": "firebase deploy --only hosting,functions:app",`
`    "deploy-functions": "firebase deploy --only functions:greetings",`
`    "deploy-all": "firebase deploy",`

As you can check I delete yarn firebase and make it firebase only and it's working great!

I hope you found this solution good for you and good luck!

**Comment by paintedbicycle** [comment]
Yes, I have found that moving to use the global firebase-tools to be the least error-prone format. I had it working fine as in the repo, but after struggling with many issues, had to move to this.

**Comment by jthegedus** [comment]
I try to avoid the global config as it causes issues across machines/developers as you cannot set a min `firebase-tools` version number in any firebase config. Glad you found a solution.

I am deprecating this example in favor of a different approach in my other repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).
