### ISSUE TITLE
Image assets

### ISSUE THREAD

**Issue by paintedbicycle** [jthegedus/firebase-functions-next-example#24]
Hello,

I tried adding images, but since this repo changes /static/ to /public/, it appears images break.

So,

1. I renamed src/public/ to src/static all told yarn functions to use /static/ inside package.json
2. I rebuilt
3. Ran `yarn run dev` -> but images don't work
4. Ran `yarn run serve` -> images _do_ work, but you cannot have the` /static/` path in them inside your image src in the page code. i.e.:

`<img src="image.jpg" />`
not
`<img src="/static/image.jpg "/>` from the next.js docs.

So, when I serve locally I can see the images. But this is only halfway working. It's hard to dev.

1. Are others seeing what I'm seeing?
2. Any way to have images working all the time?
3. Any issue with changing back to /static instead of /public?

**Comment by Jonovono** [comment]
@paintedbicycle this is my issue as well, how did you resolve?

**Comment by paintedbicycle** [comment]
@Jonovono 

If I remember correctly, I added an extra static folder. 

`/src/static` that copies to `/src/app/static`

and then I added a build step:

`package.json`:
```
    "copy-static": "cpx \"src/static/**/*.*\" \"src/app/static\" -C",
```

Now I have two static folders in src but really it's just one that then gets duplicated at build time. Over in dist I have it in `dist/functions/static`

In the HTML, I use `<img src="/static/asset.png" />`

Now it works locally in both `dev` and `serve` modes

Paul

**Comment by Jonovono** [comment]
ah got it, thanks @paintedbicycle
