### ISSUE TITLE
Incorporating Firebase Auth

### ISSUE THREAD

**Issue by technoplato** [jthegedus/firebase-functions-next-example#27]
Hey James! Thank you so much for your articles and code. It helped me get started with my website knophy.com. I've still got a lot of learning to do, but you really helped.

To the point: In this example (https://github.com/zeit/next.js/tree/canary/examples/with-firebase-authentication), Firebase Auth is baked into the request from the server using express. 

I tried to set this up [1] (naively and ignorantly) within the Firebase cloud function, but it isn't working. Can you help me figure out or offer a better solution for saving the user in the request object so we can access it server side?

[1] https://github.com/technoplato/knophy/commit/67109aebf6c45d763ac31ee4f026e6384683cc96

Thanks in advance!

**Comment by jthegedus** [comment]
Hi mate, sorry for not ever getting back to you. I am deprecating this example in favor of a different approach in my other repo (https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs).

Regarding the Auth question, this is something I am going to be looking at soon and setting up my own bunch of patterns with SSR on Firebase (though I will probably use Cloud Run over Cloud Functions going forward, not that it will change the implementation of the Auth stuff).
