### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ibrhm-mnf** [jthegedus/firebase-functions-next-example#28]
When i run "yarn serve" command in windows, it throws an error like below:

yarn run v1.2.0
$ yarn build-public && yarn build-funcs && yarn build-app && yarn copy-deps && yarn install-deps
Successfully compiled 4 files with Babel.
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pureth** [comment]
A work around is to prepend the scripts in package.json with `SET `. 

E.g.
`"serve": "NODE_ENV=production yarn firebase serve --only functions,hosting",`
->
`"serve": "SET NODE_ENV=production yarn firebase serve --only functions,hosting",`

**Comment by lehoanhao** [comment]
on Window. change it to; "SET NODE_ENV..."
