### ISSUE TITLE
babel-runtime issues

### ISSUE THREAD

**Issue by kylehotchkiss** [jthegedus/firebase-functions-next-example#5]
Hey @jthegedus,

I tried to get fancy with some spread operators and firebase cloud functions was throwing Babel issues.

```
handleChange( event ) {
        this.setState({
            ...this.state,
            fields: {
                ...this.state.fields,
                [ event.target.name ]: event.target.value 
            }
        })
    }
```

Error thrown by Firebase functions:

```
{ Error: Cannot find module 'babel-runtime/helpers/defineProperty'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/next/dist/pages/donate/index.js:7:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
```

~I was able to fix by `yarn add babel-runtime` in `src/app`.~ I thought I got it working like with this command but no combination of adding babel runtime will allow me to compile locally and on firebase functions

**Comment by jthegedus** [comment]
The reason I went with this file structure is that I too had problems using Babel. Next.js searches for Babel files higher in the path and uses those if found which causes problems with its own internal Babel settings. Where were you putting the Babel file and where were you using the spread operator?

**Comment by moooji** [comment]
I have a very similar issue. I changed the sample to use React classes like this in `pages/index.js`

```
import React from "react";
import Header from "../components/Header";

class Index extends React.Component {
  render() {
    return (
      <div>
        <Header />
        <p>Hello</p>
      </div>
    );
  }
}

export default Index;
```

This leads to a 500 and a similar Babel issue in the logs: `Cannot find module 'babel-runtime/core-js/object/get-prototype-of'`

**Comment by moooji** [comment]
@kylehotchkiss I think your solution was actually pretty close. I just did a `npm i babel-runtime --save` in the `functions` folder (not the `app`) and it seems to work so far.

**Comment by jthegedus** [comment]
Hey all, I've got a new solution coming out over the weekend that should solve this problem, it's a much simpler setup. Thanks for taking the time to post and sharing your solutions :smile:

**Comment by gulukul** [comment]
@jthegedus I am facing similar problems. Please post your solution :)

Thank you.

**Comment by flexlee** [comment]
@jthegedus Thanks for the solution. Is your post coming out soon?

**Comment by jthegedus** [comment]
@gulukul The new code is live on this repo, give it a read to see the changes before running. It should solve this particular problem (and some other issues).

@flexlee I'm writing it atm, should be published before this coming weekend. It'll explain everything from scratch (not assuming any knowledge of the prior implementation).

Sorry for the delay but I've spread myself too thin and haven't been able to get around to everything. I'm starting to get on top of everything. Triaging my repos and getting these associated blog posts out is priority 1. Thanks for your patience.

**Comment by jthegedus** [comment]
I'll consider this closed since this is no longer a problem with the new repo example. I'm still working on the new Medium post which I will link here when finished (or you can [follow me on Medium](https://medium.com/@jthegedus) to get real-time updates.
