### ISSUE TITLE
Cloud functions logs throws error cannot find module

### ISSUE THREAD

**Issue by andreikho** [jthegedus/firebase-functions-next-example#6]
"Cannot find module next\dist\server\document.js"
"Cannot find module next\dist\lib\error.js"

and throws in error 500 ... and I did not forget the trailing slash

maybe has to do with the version of Next? I'm not sure what "beta" version refers to

Edit: it works in development locally, just not on cloud functions

**Comment by andreikho** [comment]
Doesn't work on windows, tried on mac&ubuntu worked just fine... I guess because paths don't match... still no idea how to fix it

**Comment by webeli** [comment]
I get the same issue (on windows 10).

I've run `yarn install`, `yarn build-all`, `yarn preserve`.

`yarn next` works to run it in develop mode. But `yarn deploy` and `yarn serve` does not:

![image](https://user-images.githubusercontent.com/3446889/31853468-1a0ef0b8-b689-11e7-8120-60533f2ab3da.png)

Cloud functions error:

![image](https://user-images.githubusercontent.com/3446889/31853470-2e19abde-b689-11e7-973b-b1a66edd3b46.png)

**Comment by pt7892** [comment]
Hey guys, I had the same problem with this issues on windows 10. Managed to get it work by manually changing the path of required modules. If you check files: 

functions/next/dist/components/Header.js, 
functions/next/dist/pages/_document.js, 
functions/next/dist/pages/_error.js 

you will see: 

```
var _link = require('next\\dist\\lib\\link.js');
module.exports = require('next\\dist\\server\\document.js');
module.exports = require('next\dist\\lib\\error.js');`
```

Changing require paths from `"\\"` to `"/"` fixes the issue

**Comment by jthegedus** [comment]
Next.js 5 came out recently where loading the `_document` and `_error` files was a problem. I've since updated this example with a canary release of Next.js which accounts for this problem. Closing this now, but if you run into similar issues with the updated repo then please do create another issue. Cheers.
